const TZ_TO_COUNTRY: Record<string, string> = {
  'Africa/Luanda': 'AO', 'Africa/Lagos': 'NG', 'Africa/Nairobi': 'KE',
  'Africa/Cairo': 'EG', 'Africa/Johannesburg': 'ZA', 'Africa/Accra': 'GH',
  'Africa/Casablanca': 'MA', 'Africa/Abidjan': 'CI', 'Africa/Addis_Ababa': 'ET',
  'Africa/Kampala': 'UG', 'Africa/Dar_es_Salaam': 'TZ', 'Africa/Khartoum': 'SD',
  'Africa/Maputo': 'MZ', 'Africa/Douala': 'CM', 'Africa/Kinshasa': 'CD',
  'Africa/Dakar': 'SN', 'Africa/Algiers': 'DZ', 'Africa/Tunis': 'TN',
  'Africa/Tripoli': 'LY', 'Africa/Harare': 'ZW', 'Africa/Lusaka': 'ZM',
  'Africa/Windhoek': 'NA',
  'Europe/Lisbon': 'PT', 'Europe/London': 'GB', 'Europe/Paris': 'FR',
  'Europe/Berlin': 'DE', 'Europe/Madrid': 'ES', 'Europe/Rome': 'IT',
  'Europe/Amsterdam': 'NL', 'Europe/Brussels': 'BE', 'Europe/Vienna': 'AT',
  'Europe/Zurich': 'CH', 'Europe/Stockholm': 'SE', 'Europe/Oslo': 'NO',
  'Europe/Copenhagen': 'DK', 'Europe/Helsinki': 'FI', 'Europe/Warsaw': 'PL',
  'Europe/Prague': 'CZ', 'Europe/Budapest': 'HU', 'Europe/Bucharest': 'RO',
  'Europe/Athens': 'GR', 'Europe/Istanbul': 'TR', 'Europe/Moscow': 'RU',
  'Europe/Kiev': 'UA', 'Europe/Kyiv': 'UA', 'Europe/Dublin': 'IE',
  'Europe/Riga': 'LV', 'Europe/Tallinn': 'EE', 'Europe/Vilnius': 'LT',
  'Europe/Sofia': 'BG',
  'America/New_York': 'US', 'America/Chicago': 'US', 'America/Denver': 'US',
  'America/Los_Angeles': 'US', 'America/Anchorage': 'US', 'America/Honolulu': 'US',
  'America/Sao_Paulo': 'BR', 'America/Manaus': 'BR', 'America/Toronto': 'CA',
  'America/Vancouver': 'CA', 'America/Mexico_City': 'MX', 'America/Bogota': 'CO',
  'America/Lima': 'PE', 'America/Santiago': 'CL',
  'America/Argentina/Buenos_Aires': 'AR', 'America/Caracas': 'VE',
  'America/Havana': 'CU', 'America/Santo_Domingo': 'DO', 'America/Guatemala': 'GT',
  'America/Montevideo': 'UY', 'America/La_Paz': 'BO', 'America/Asuncion': 'PY',
  'America/Guayaquil': 'EC', 'America/Panama': 'PA',
  'Asia/Tokyo': 'JP', 'Asia/Shanghai': 'CN', 'Asia/Seoul': 'KR',
  'Asia/Singapore': 'SG', 'Asia/Dubai': 'AE', 'Asia/Kolkata': 'IN',
  'Asia/Bangkok': 'TH', 'Asia/Jakarta': 'ID', 'Asia/Taipei': 'TW',
  'Asia/Hong_Kong': 'HK', 'Asia/Kuala_Lumpur': 'MY', 'Asia/Manila': 'PH',
  'Asia/Karachi': 'PK', 'Asia/Dhaka': 'BD', 'Asia/Riyadh': 'SA',
  'Asia/Tehran': 'IR', 'Asia/Baghdad': 'IQ', 'Asia/Beirut': 'LB',
  'Asia/Jerusalem': 'IL', 'Asia/Almaty': 'KZ',
  'Australia/Sydney': 'AU', 'Australia/Melbourne': 'AU', 'Australia/Perth': 'AU',
  'Pacific/Auckland': 'NZ', 'Pacific/Honolulu': 'US',
};

export function getCountryFromTimezone(tz: string, fallback = 'AO'): string {
  return TZ_TO_COUNTRY[tz] ?? fallback;
}
